### ISSUE TITLE
DrawerDialog BehaviorType.RIGHT，move event crash

### ISSUE THREAD

**Issue by donglua** [microsoft/fluentui-android#298]
### Environment Information

- **Package version(s)**: 0.1.12
- **Android SDK version**: 33

#### Actual behavior:

```
  java.lang.NullPointerException
   at com.microsoft.fluentui.drawer.SideSheetBehavior$dragCallback$1.tryCaptureView(SideSheetBehavior.kt:534)
   at androidx.customview.widget.ViewDragHelper.tryCaptureViewForDrag(ViewDragHelper.java:941)
   at androidx.customview.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1095)
   at com.microsoft.fluentui.drawer.SideSheetBehavior.onInterceptTouchEvent(SideSheetBehavior.kt:189)
   at androidx.coordinatorlayout.widget.CoordinatorLayout.performEvent(CoordinatorLayout.java:548)
   at androidx.coordinatorlayout.widget.CoordinatorLayout.performIntercept(CoordinatorLayout.java:503)
   at androidx.coordinatorlayout.widget.CoordinatorLayout.onInterceptTouchEvent(CoordinatorLayout.java:570)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2652)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
   at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:537)
   at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1925)
   at android.app.Dialog.dispatchTouchEvent(Dialog.java:864)
   at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
```

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

**Comment by joyeeta26** [comment]
Hey @donglua, this doen't seem to repro in the latest version. Closing this issue. Please feel free to reopen if it's still happening for you. Thanks!
cc: @Dhoot
