### ISSUE TITLE
CCB Crashes when long pressing item without providing optional LongPressItemClicked handler

### ISSUE THREAD

**Issue by caltseng** [microsoft/fluentui-android#357]
https://github.com/microsoft/fluentui-android/blame/6ca47840f4800aea7505eaf7c9e99726ce5314f0/fluentui_ccb/src/main/java/com/microsoft/fluentui/contextualcommandbar/CommandItemAdapter.kt

Line 163 - itemLongClickListener?.onItemLongClick(commandItem, viewHolder.itemView)!!

The !! should be removed (!! is poor Kotlin practice to begin with). 

```
06:48:25.109  E  FATAL EXCEPTION: main
                 Process: com.microsoft.loop, PID: 1039
                 java.lang.NullPointerException
                 	at com.microsoft.fluentui.contextualcommandbar.CommandItemAdapter.onBindViewHolder$lambda-10$lambda-8(CommandItemAdapter.kt:163)
                 	at com.microsoft.fluentui.contextualcommandbar.CommandItemAdapter.$r8$lambda$cdZ99B0JC_fofd91lIU4hr8dKck(Unknown Source:0)
                 	at com.microsoft.fluentui.contextualcommandbar.CommandItemAdapter$$ExternalSyntheticLambda0.onLongClick(Unknown Source:6)
                 	at android.view.View.performLongClickInternal(View.java:7961)
                 	at android.view.View.performLongClick(View.java:7919)
                 	at android.view.View.performLongClick(View.java:7937)
                 	at android.view.View$CheckForLongPress.run(View.java:30821)
                 	at android.os.Handler.handleCallback(Handler.java:942)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:226)
                 	at android.os.Looper.loop(Looper.java:313)
                 	at android.app.ActivityThread.main(ActivityThread.java:8741)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
06:48:25.135  E  Uncaught exception in app
                 java.lang.NullPointerException
                 	at com.microsoft.fluentui.contextualcommandbar.CommandItemAdapter.onBindViewHolder$lambda-10$lambda-8(CommandItemAdapter.kt:163)
                 	at com.microsoft.fluentui.contextualcommandbar.CommandItemAdapter.$r8$lambda$cdZ99B0JC_fofd91lIU4hr8dKck(Unknown Source:0)
                 	at com.microsoft.fluentui.contextualcommandbar.CommandItemAdapter$$ExternalSyntheticLambda0.onLongClick(Unknown Source:6)
                 	at android.view.View.performLongClickInternal(View.java:7961)
                 	at android.view.View.performLongClick(View.java:7919)
                 	at android.view.View.performLongClick(View.java:7937)
                 	at android.view.View$CheckForLongPress.run(View.java:30821)
                 	at android.os.Handler.handleCallback(Handler.java:942)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:226)
                 	at android.os.Looper.loop(Looper.java:313)
                 	at android.app.ActivityThread.main(ActivityThread.java:8741)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by vishnu2410** [comment]
Issue is fixed by this PR
https://github.com/microsoft/fluentui-android/pull/360
